### ISSUE TITLE
Couldn't create a Convex Mesh from source mesh "hip" within the maximum polygons limit (256). 

### ISSUE THREAD

**Issue by singingwithcode** [Unity-Technologies/com.unity.cv.synthetichumans#8]
Greetings, I am brand new to Unity and followed your tutorial to a T! Everything works as expected except I get this warning several times:

**Couldn't create a Convex Mesh from source mesh "hip" within the maximum polygons limit (256). The partial hull will be used. Consider simplifying your mesh. UnityEngine.StackTraceUtility:ExtractStackTrace ()**

It appears with "hip" (as above), "spine_03", "elbow_left", "head", etc. 
Is this limiting the quality as well? 

I am using:
- Unity 2021.3.23f1
- Perception 1.0.0-preview.1
- Synthetic Humans 0.1.0

**Comment by peifeng-unity** [comment]
Hi @singingwithcode, it is great to hear from you. The warnings don't mean lower or limited quality in the generated image. They are caused by the collision meshes instead of the rendering meshes. In Unity, synthetic humans use rendering meshes for image generation and use collision meshes only for placement. The rendering meshes have high resolution/quality. The collision meshes are auto-generated from the rendering mesh. However, Unity can only support as many as 256 vertices in a convex collision mesh. Therefore, it has a lower quality in collision detection, but the rendering meshes keep a high resolution and high quality.

**Comment by singingwithcode** [comment]
Thank you so much @peifeng-unity. This makes sense to me!

**Comment by moonsh** [comment]
@peifeng-unity Is there a way to disable to get the warning messages?

**Comment by csun** [comment]
Hey Seonghyeon - if you don't need colliders on your humans you can go into your Human generation config and disable collider generation. If you do need the colliders on there's unfortunately nothing that I know of that you can do about the warnings.
